export const SET_WIDTH_DEVICE = "SET_WITDTH_DEVICE";
export const GET_ALL_RECIPES = "GET ALL RECIPES";
export const GET_DIETS = "GET_DIETS";
export const PAGINADO = "PAGINADO";
export const STATE_OF_SEARCH_BAR = 'STATE_OF_SEACH_BAR';
export const RECIPES_BY_DIET = 'RECIPES_BY_DIET';
export const CHANGE_ORDER = 'CHANGE_ORDER';
export const GET_RECIPE_DETAILS = 'GET_DETAILS';
export const LOADING_CARDS_CONTAINER = "LOADING_CARDS_CONTAINER";
export const DARK_MODE = "DARK_MODE";


